In [1]:
#Importing numpy as the main library
import numpy as np
# I import main_functions which will have functions such as activation functions and others
from main_functions import *

In [2]:
# Initializing weights randomly by neurons per layer and the number of layers
def init_weights(number_layers, neurons_by_layer):
    #Initializing weights and biases.
    weights = {}
    biases = {}
    
    #Doing a for loop across all the layers.
    for l in range(1, number_layers):
        #Returning random values of weights from the layer number l
        weights["W" + str(l)] = np.random.rand(neurons_by_layer[l], neurons_by_layer[l-1])
        biases["b" + str(l)] = np.random.rand(neurons_by_layer[l],1)
    
    return weights, biases    

In [7]:
#Draft where I implement ideas
A_prev = np.ones([4,3])
W = np.ones([5,4])
b = np.zeros([5,1])
print("A_previous:" + str(A_prev))
print("W of this layer: " + str(W))
print("b: " + str(b))

print(forward_activation(W, A_prev, b, activation_name='sigmoid'))

A_previous:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
W of this layer: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
b: [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.01798621 0.01798621 0.01798621]
 [0.01798621 0.01798621 0.01798621]
 [0.01798621 0.01798621 0.01798621]
 [0.01798621 0.01798621 0.01798621]
 [0.01798621 0.01798621 0.01798621]]
