In [1]:
#Importing numpy as the main library
import numpy as np
# I import main_functions which will have functions such as activation functions and others
from main_functions import *

In [2]:
# Initializing weights randomly by neurons per layer and the number of layers
def init_weights(number_layers, neurons_by_layer):
    #Initializing weights and biases.
    weights = {}
    biases = {}
    
    #Doing a for loop across all the layers.
    for l in range(1, number_layers):
        #Returning random values of weights from the layer number l
        weights["W" + str(l)] = np.random.rand(neurons_by_layer[l], neurons_by_layer[l-1])
        biases["b" + str(l)] = np.random.rand(neurons_by_layer[l],1)
    
    return weights, biases    

In [26]:
def forward_iteration():
    pass


In [22]:
#Draft where I implement ideas
A_prev = np.random.randn(3,4)
W = np.random.randint(low=0,high=4, size=(3,3))
b = np.zeros([5,1])
print("A_previous:" + str(A_prev))
print("W of this layer: " + str(W))
print("b: " + str(b))

assert (A_prev!=A_prev).all()

A_previous:[[ 0.63947933  1.1817889  -0.3261038  -0.26595113]
 [-1.7090504  -0.24102012  1.48522882 -0.5079276 ]
 [-0.25136176  0.05671912  0.61469295 -1.28455993]]
W of this layer: [[1 2 0]
 [3 2 0]
 [2 1 1]]
b: [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


AssertionError: 